# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt        # Check if code is formatted with gofmt
    - govet        # Examines Go source code and reports suspicious constructs
    - errcheck     # Check for unchecked errors
    - staticcheck  # Go static analysis
    - unused       # Check for unused constants, variables, functions and types
    - gosimple     # Simplify code
    - ineffassign  # Detect ineffectual assignments
    - typecheck    # Type-check code
    - misspell     # Find commonly misspelled words
    - gocyclo      # Compute cyclomatic complexities
    - gosec        # Security issues
    - unconvert    # Remove unnecessary type conversions
    - goconst      # Find repeated strings that could be replaced by a constant
    - dupl         # Find duplicated code
    - prealloc     # Find slice declarations that could potentially be preallocated

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G204  # Subprocess with variable (needed for Docker operations)
      - G304  # File path provided as taint input (needed for config files)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

    # Exclude known issues
    - text: weak cryptographic primitive
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
