version: '3.9'

services:
  docker:
    image: docker:26-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    volumes:
      - docker-data:/var/lib/docker
      - shared-tmp:/tmp

  docker-proxy:
    image: hypolas/dockershield:latest
    depends_on:
      - docker
    environment:
      DOCKER_SOCKET: tcp://docker:2375
      LISTEN_ADDR: :2375
      LISTEN_SOCKET: unix:///tmp/dockershield.sock
      SOCKET_PERMS: "0660"
      CONTAINERS: 1
      IMAGES: 1
      POST: 0
      DELETE: 0
    ports:
      - 127.0.0.1:12375:2375
    volumes:
      - shared-tmp:/tmp

  client:
    image: docker:26-cli
    depends_on:
      - docker-proxy
    environment:
      DOCKER_HOST: tcp://docker-proxy:2375
    volumes:
      - shared-tmp:/tmp
    command: ["sleep", "infinity"]

volumes:
  docker-data:
  shared-tmp:
